import { Achievement, HealthMilestone } from '../types';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_day',
    title: '第一天',
    description: '成功戒烟1天',
    unlockedAt: null,
    icon: 'star',
    requirement: 1,
    type: 'days',
  },
  {
    id: 'one_week',
    title: '一周',
    description: '连续戒烟7天',
    unlockedAt: null,
    icon: 'calendar',
    requirement: 7,
    type: 'days',
  },
  {
    id: 'one_month',
    title: '一个月',
    description: '连续戒烟30天',
    unlockedAt: null,
    icon: 'calendar-check',
    requirement: 30,
    type: 'days',
  },
  {
    id: 'three_months',
    title: '三个月',
    description: '连续戒烟90天',
    unlockedAt: null,
    icon: 'award',
    requirement: 90,
    type: 'days',
  },
  {
    id: 'six_months',
    title: '半年',
    description: '连续戒烟180天',
    unlockedAt: null,
    icon: 'trophy',
    requirement: 180,
    type: 'days',
  },
  {
    id: 'one_year',
    title: '一年',
    description: '连续戒烟365天',
    unlockedAt: null,
    icon: 'crown',
    requirement: 365,
    type: 'days',
  },
  {
    id: 'first_record',
    title: '初学者',
    description: '完成首次戒烟打卡',
    unlockedAt: null,
    icon: 'check-circle',
    requirement: 1,
    type: 'records',
  },
  {
    id: 'ten_records',
    title: '坚持不懈',
    description: '完成10次戒烟打卡',
    unlockedAt: null,
    icon: 'thumbs-up',
    requirement: 10,
    type: 'records',
  },
  {
    id: 'fifty_records',
    title: '意志坚定',
    description: '完成50次戒烟打卡',
    unlockedAt: null,
    icon: 'heart',
    requirement: 50,
    type: 'records',
  },
  {
    id: 'save_100',
    title: '省钱达人',
    description: '累计节省100元',
    unlockedAt: null,
    icon: 'dollar-sign',
    requirement: 100,
    type: 'money',
  },
  {
    id: 'save_500',
    title: '理财高手',
    description: '累计节省500元',
    unlockedAt: null,
    icon: 'credit-card',
    requirement: 500,
    type: 'money',
  },
  {
    id: 'save_1000',
    title: '健康投资家',
    description: '累计节省1000元',
    unlockedAt: null,
    icon: 'briefcase',
    requirement: 1000,
    type: 'money',
  },
];

export const HEALTH_MILESTONES: HealthMilestone[] = [
  {
    id: '20min',
    title: '20分钟后',
    description: '血压和心率恢复正常',
    timeAfterQuit: '20分钟',
    timeInDays: 0,
    benefits: ['血压恢复正常', '心率恢复正常', '心血管系统开始恢复'],
  },
  {
    id: '8h',
    title: '8小时后',
    description: '血液中一氧化碳水平降至正常',
    timeAfterQuit: '8小时',
    timeInDays: 0,
    benefits: ['血液中一氧化碳水平正常', '氧气水平恢复正常', '身体开始清除烟草毒素'],
  },
  {
    id: '48h',
    title: '48小时后',
    description: '味觉和嗅觉开始改善',
    timeAfterQuit: '48小时',
    timeInDays: 2,
    benefits: ['味觉改善', '嗅觉改善', '食物味道更美味'],
  },
  {
    id: '2w',
    title: '2周后',
    description: '肺功能开始改善',
    timeAfterQuit: '2周',
    timeInDays: 14,
    benefits: ['肺功能改善', '呼吸更顺畅', '体力增强'],
  },
  {
    id: '1m',
    title: '1个月后',
    description: '血液循环明显改善',
    timeAfterQuit: '1个月',
    timeInDays: 30,
    benefits: ['血液循环改善', '皮肤状态改善', '精力更充沛'],
  },
  {
    id: '3m',
    title: '3个月后',
    description: '肺功能改善30%',
    timeAfterQuit: '3个月',
    timeInDays: 90,
    benefits: ['肺功能显著改善', '咳嗽减少', '呼吸短促减少'],
  },
  {
    id: '6m',
    title: '6个月后',
    description: '慢性咳嗽和气喘明显减少',
    timeAfterQuit: '6个月',
    timeInDays: 180,
    benefits: ['慢性咳嗽减少', '气喘减少', '肺功能持续改善'],
  },
  {
    id: '1y',
    title: '1年后',
    description: '冠心病风险降至一半',
    timeAfterQuit: '1年',
    timeInDays: 365,
    benefits: ['冠心病风险降低50%', '心脏健康显著改善', '寿命延长'],
  },
  {
    id: '5y',
    title: '5年后',
    description: '中风风险降至正常水平',
    timeAfterQuit: '5年',
    timeInDays: 1825,
    benefits: ['中风风险正常', '口腔癌风险降低', '食道癌风险降低'],
  },
  {
    id: '10y',
    title: '10年后',
    description: '肺癌风险降低50%',
    timeAfterQuit: '10年',
    timeInDays: 3650,
    benefits: ['肺癌风险降低50%', '胰腺癌风险降低', '整体癌症风险显著降低'],
  },
  {
    id: '15y',
    title: '15年后',
    description: '冠心病风险降至正常',
    timeAfterQuit: '15年',
    timeInDays: 5475,
    benefits: ['冠心病风险正常', '身体全面恢复', '接近非吸烟者健康水平'],
  },
];

export const MOTIVATIONAL_QUOTES = [
  '每一次不抽烟的决定，都是对自己健康的投资。',
  '戒烟不是放弃，而是选择更好的生活。',
  '你现在的坚持，是未来健康的基石。',
  '烟瘾只是一时的冲动，健康是一生的财富。',
  '坚持就是胜利，每一天都是新的开始。',
  '你的肺部正在感谢你的每一个决定。',
  '戒烟不是终点，而是美好生活的起点。',
  '相信自己，你可以做到！',
  '每一次克服烟瘾，都是一次胜利。',
  '健康的身体是最大的自由。',
  '今天的选择，决定明天的生活。',
  '戒烟的路上，你并不孤单。',
];
